version: "3.1"

services:
       
    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: pwakey
            POSTGRES_USER: pwauser
            POSTGRES_DB: pwa
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data:delegated
        ports:
            - '5432:5432'