version: "3.1"

services:
    app:
        image: yiisoftware/yii2-php:8.1-apache
        volumes: 
            - ./backend/composer/cache:/root/.composer/cache:delegated
            - ./backend/basic:/app:delegated
        environment: 
            DB_DATABASE: pwa
            DB_PASSWORD: pwakey
            DB_USER: pwauser
            DB_HOST: db
            PHP_USER_ID: 1000
            PRODUCCION: 0
            
        ports: 
            - 8000:80
            
    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: zkgaren@gmail.com
            PGADMIN_DEFAULT_PASSWORD: emi123
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin:delegated
        ports: 
            - 8001:80        

    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: pwakey
            POSTGRES_USER: pwauser
            POSTGRES_DB: pwa
        volumes:
            - ./data/pgdata:/var/lib/postgresql/data:delegated
        ports:
            - '5432:5432'